controller_list:
  - name: fake_ur5_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint
      - gripper_joint1
      - gripper_joint2
      - gripper_joint3
      - gripper_joint4
      - gripper_joint5
      - gripper_joint6
      - gripper_joint7
      - gripper_joint8
initial:  # Define initial robot poses.
  - group: ur5_arm
    pose: up